const express=require('express')
const mongo=require('mongoose')
const PORT=3000
const app=express()
app.use(express.json())
app.use(express.urlencoded({extended:true}))
const User=require("./models/User.js")
const Trip=require("./models/Trip.js")
const TripStop=require("./models/TripStop.js")
const Activity=require("./models/Activity.js")
mongo.connect(`mongodb+srv://GlobeTrotter:GlobeTrotter2026@cluster0.z97tamy.mongodb.net/GlobeTrotter`).then(()=>{
    console.log("Mongo connected to atlas")
})
const userRoutes=require("./routes/userRoutes.js")
app.use("/",userRoutes)
app.get("/user",User)
app.get("/trip",Trip)
app.get("/tripstop",TripStop)
app.get("/activity",Activity)
app.listen(PORT,()=>{
    console.log(`listening on port ${PORT}`)
})